lib: [
  "_build/install/default/lib/perceptron/META"
  "_build/install/default/lib/perceptron/dune-package"
  "_build/install/default/lib/perceptron/opam"
  "_build/install/default/lib/perceptron/perceptron.a"
  "_build/install/default/lib/perceptron/perceptron.cma"
  "_build/install/default/lib/perceptron/perceptron.cmi"
  "_build/install/default/lib/perceptron/perceptron.cmt"
  "_build/install/default/lib/perceptron/perceptron.cmx"
  "_build/install/default/lib/perceptron/perceptron.cmxa"
  "_build/install/default/lib/perceptron/perceptron.ml"
]
libexec: [
  "_build/install/default/lib/perceptron/perceptron.cmxs"
]
bin: [
  "_build/install/default/bin/perceptron"
]
